packages:
  - apps/*
  - packages/*

overrides:
  '@unrs/resolver-binding-wasm32-wasi@1.12.2>@napi-rs/wasm-runtime': 1.1.6

allowBuilds:
  esbuild: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - '@posthog/core@1.52.0'
  - '@posthog/types@1.409.4'
  - posthog-react-native@4.68.4
