import { useCallback } from 'react';

import { useProductAnalytics } from '@/features/analytics/application/use-product-analytics';
import { ANALYTICS_SCHEMA_VERSION } from '@/features/analytics/domain/analytics-events';
import {
  composedPieceCount,
  composeResultProperty,
  generationModeProperty,
  outfitSlotProperty,
  wornSourceProperty,
} from '@/features/analytics/domain/analytics-mappers';
import type { OutfitRecommendationResult } from '@/features/recommendation/application/recommend-outfits';
import type { OutfitSlot } from '@/features/recommendation/domain/outfit-composition';
import type { WornOutfit } from '@/features/recommendation/domain/outfit-history';

/**
 * What outfit detail reports about the reader's own work on it (taxonomy 5.6): one piece
 * changed, and a compose around chosen pieces settled. `position` is the opened outfit's place
 * among Today's three, absent for an idea; a composed result has no place and omits it.
 * Tomorrow's preview reports neither.
 */
export function useOutfitEditReports(input: Readonly<{
  tomorrow: boolean;
  position: 1 | 2 | 3 | null;
}>) {
  const { tomorrow, position } = input;
  const { analytics } = useProductAnalytics();
  const onPieceChanged = useCallback((slot: OutfitSlot, composed: boolean) => {
    if (tomorrow) return;
    analytics.capture('outfit_piece_changed', {
      schema_version: ANALYTICS_SCHEMA_VERSION,
      slot: outfitSlotProperty(slot),
      ...(position && !composed ? { outfit_position: position } : {}),
    });
  }, [analytics, position, tomorrow]);
  const onComposed = useCallback((pieceCount: number, optionCount: number) => {
    if (tomorrow || pieceCount === 0) return;
    analytics.capture('outfit_composed', {
      schema_version: ANALYTICS_SCHEMA_VERSION,
      piece_count: composedPieceCount(pieceCount),
      result: composeResultProperty(optionCount),
    });
  }, [analytics, tomorrow]);
  return { onPieceChanged, onComposed };
}

/**
 * Taxonomy 5.6's `outfit_worn_logged`, for the History write that just succeeded. The source
 * is mapped from the stored record plus whether a composed result was showing. The generation
 * mode is the day's recommendation's, only for one of the three as kuyara picked or the
 * reader edited it: a composed result and an idea were not generated by that mode.
 */
export function useOutfitWornLoggedReport(input: Readonly<{
  composed: boolean;
  position: 1 | 2 | 3 | null;
  recommendation: OutfitRecommendationResult | null;
}>) {
  const { composed, position, recommendation } = input;
  const { analytics } = useProductAnalytics();
  const generationMode = !composed && position && recommendation?.status === 'recommended'
    ? generationModeProperty(recommendation.generationMode) : null;
  return useCallback((worn: WornOutfit) => {
    analytics.capture('outfit_worn_logged', {
      schema_version: ANALYTICS_SCHEMA_VERSION,
      worn_source: wornSourceProperty(worn.source, composed),
      archetype: worn.archetypeId,
      dress_style: worn.formality,
      ...(generationMode ? { generation_mode: generationMode } : {}),
    });
  }, [analytics, composed, generationMode]);
}
