import { weatherLocalDateKey } from '@kuyara/contracts';

import {
  defaultQuietHours,
  isWetMeasurement,
} from '@/features/notifications/domain/weather-alerts';
import type {
  HourlyWeather,
  WeatherConditionCode,
  WeatherSnapshot,
} from '@/features/weather/domain/weather';

/**
 * ADR 0004: the second notification kind. The briefing is the one notification that arrives
 * on an ordinary morning, so it is planned from tomorrow's hours rather than from a rule
 * crossing. It composes nothing: the recommendation is generated by its own approved
 * triggers when the person opens Today, and this module only projects the weather the
 * morning will bring.
 *
 * The projection is pure and structural. No copy, no clothing requirement, no identifier,
 * and nothing is invented: a snapshot whose hourly window does not reach tomorrow's morning
 * hour plans nothing at all.
 */

/** The briefing fires as quiet hours end, so it can never fall inside them. */
export const morningBriefingLocalHour = defaultQuietHours.end.hour;
/** The last hour the projection reads, so the range describes a morning and not a day. */
export const morningBriefingLastLocalHour = 11;

export type MorningBriefingContent = Readonly<{
  minimumTemperatureCelsius: number;
  maximumTemperatureCelsius: number;
  /** The condition at the hour the briefing arrives. */
  condition: WeatherConditionCode;
  precipitationLikely: boolean;
}>;

export type MorningBriefingPlan = Readonly<{
  id: string;
  localDate: string;
  fireAt: string;
  content: MorningBriefingContent;
}>;

export function morningBriefingId(localDate: string): string {
  return `morning_briefing:${localDate}`;
}

function nextLocalDate(localDate: string): string {
  const [year, month, day] = localDate.split('-').map(Number);
  // Calendar arithmetic on the date key itself: a local date has no offset to carry, so
  // UTC is only the arithmetic here and never a time zone claim.
  return new Date(Date.UTC(year, month - 1, day + 1)).toISOString().slice(0, 10);
}

// The same fixed 'en' locale and h23 cycle the quiet-hours comparison uses: this reads an
// hour as a 0-23 number whatever the device's 12/24-hour setting says.
function localHour(timestamp: string, timeZone: string): number | null {
  const hour = Number(new Intl.DateTimeFormat('en', {
    timeZone,
    hour: '2-digit',
    hourCycle: 'h23',
  }).format(new Date(timestamp)));
  return Number.isInteger(hour) ? hour : null;
}

/**
 * Plans tomorrow morning's briefing from an already-validated snapshot, or nothing when the
 * snapshot's hourly window does not reach the morning hour.
 */
export function planMorningBriefing(input: Readonly<{
  snapshot: WeatherSnapshot;
  now: string;
  deliveredIds: ReadonlySet<string>;
}>): MorningBriefingPlan | null {
  const { snapshot } = input;
  const today = weatherLocalDateKey(input.now, snapshot.timeZone);
  if (today === null) return null;

  const localDate = nextLocalDate(today);
  const id = morningBriefingId(localDate);
  if (input.deliveredIds.has(id)) return null;

  const morning: HourlyWeather[] = [];
  let briefingHour: HourlyWeather | null = null;
  for (const hour of snapshot.hourly) {
    if (weatherLocalDateKey(hour.forecastAt, snapshot.timeZone) !== localDate) continue;
    const local = localHour(hour.forecastAt, snapshot.timeZone);
    if (local === null
      || local < morningBriefingLocalHour
      || local > morningBriefingLastLocalHour) continue;
    if (local === morningBriefingLocalHour) briefingHour = hour;
    morning.push(hour);
  }

  // Without the morning hour itself there is neither a fire time nor a first reading, and
  // inventing either would be fabricated weather.
  if (!briefingHour) return null;

  const temperatures = morning.map(({ temperatureCelsius }) => temperatureCelsius);
  return Object.freeze({
    id,
    localDate,
    fireAt: briefingHour.forecastAt,
    content: Object.freeze({
      minimumTemperatureCelsius: Math.min(...temperatures),
      maximumTemperatureCelsius: Math.max(...temperatures),
      condition: briefingHour.condition,
      precipitationLikely: morning.some(isWetMeasurement),
    }),
  });
}
