import { weatherLocalDateKey } from '@kuyara/contracts';

import { calendarDateParts } from '@/domain/calendar-date';
import { zonedHour } from '@/domain/intl-format';
import { defaultQuietHours } from '@/features/notifications/domain/weather-alerts';
import type {
  HourlyWeather,
  WeatherConditionCode,
  WeatherSnapshot,
} from '@/features/weather/domain/weather';
import { findWeatherOutlook, type WeatherOutlook } from '@/features/weather/domain/weather-outlook';
import { isWetMeasurement } from '@/features/weather/domain/weather-thresholds';

/**
 * ADR 0004: the second notification kind. The briefing is the one notification that arrives
 * on an ordinary morning. It composes nothing: the recommendation is generated by its own
 * approved triggers when the person opens Today. The event follows the Weather card's
 * decision-changing transition rule, starting with the briefing hour's forecast.
 *
 * The projection is pure and structural. No copy, no clothing requirement, no identifier,
 * and nothing is invented: a snapshot whose hourly window does not reach the selected
 * briefing hour plans nothing at all. A short window is explicitly marked as partial.
 */

/** The briefing fires as quiet hours end, so it can never fall inside them. */
export const morningBriefingLocalHour = defaultQuietHours.end.hour;
/** The last hour that establishes coverage of the local calendar day. */
const lastLocalDayHour = 23;

export type MorningBriefingContent = Readonly<{
  minimumTemperatureCelsius: number;
  maximumTemperatureCelsius: number;
  /** The condition at the hour the briefing arrives. */
  condition: WeatherConditionCode;
  /** Whether the briefing hour itself is wet, by the Weather outlook's own threshold. */
  precipitationLikely: boolean;
  /** Null when the forecast includes the last hour of the local day. */
  coveredThrough: string | null;
  /** A steady outlook makes no claim about unforecast hours. */
  event: Exclude<WeatherOutlook, { kind: 'steady' }> | null;
}>;

export type MorningBriefingPlan = Readonly<{
  id: string;
  localDate: string;
  fireAt: string;
  content: MorningBriefingContent;
}>;

export function morningBriefingId(localDate: string): string {
  return `morning_briefing:${localDate}`;
}

function nextLocalDate(localDate: string): string {
  const { year, month, day } = calendarDateParts(localDate);
  // Calendar arithmetic on the date key itself: a local date has no offset to carry, so
  // UTC is only the arithmetic here and never a time zone claim.
  return new Date(Date.UTC(year, month - 1, day + 1)).toISOString().slice(0, 10);
}

/**
 * Plans the next eligible morning's briefing from an already-validated snapshot, or nothing when the
 * snapshot's hourly window does not reach the morning hour.
 */
export function planMorningBriefing(input: Readonly<{
  snapshot: WeatherSnapshot;
  now: string;
  deliveredIds: ReadonlySet<string>;
}>): MorningBriefingPlan | null {
  const { snapshot } = input;
  const today = weatherLocalDateKey(input.now, snapshot.timeZone);
  if (today === null) return null;

  const todayId = morningBriefingId(today);
  const hour = zonedHour(Date.parse(input.now), snapshot.timeZone);
  const localDate = hour < morningBriefingLocalHour && !input.deliveredIds.has(todayId)
    ? today
    : nextLocalDate(today);
  const id = morningBriefingId(localDate);
  if (input.deliveredIds.has(id)) return null;

  const dayHours: HourlyWeather[] = [];
  let briefingHour: HourlyWeather | null = null;
  for (const hour of snapshot.hourly) {
    if (weatherLocalDateKey(hour.forecastAt, snapshot.timeZone) !== localDate) continue;
    const local = zonedHour(Date.parse(hour.forecastAt), snapshot.timeZone);
    if (local < morningBriefingLocalHour) continue;
    if (local === morningBriefingLocalHour) briefingHour = hour;
    dayHours.push(hour);
  }

  // Without the morning hour itself there is neither a fire time nor a first reading, and
  // inventing either would be fabricated weather.
  if (!briefingHour) return null;

  const temperatures = dayHours.map(({ temperatureCelsius }) => temperatureCelsius);
  const outlook = findWeatherOutlook({
    snapshot: {
      ...snapshot,
      current: { ...briefingHour, observedAt: briefingHour.forecastAt },
    },
    now: briefingHour.forecastAt,
  });
  const lastHour = dayHours.at(-1)!;
  return Object.freeze({
    id,
    localDate,
    fireAt: briefingHour.forecastAt,
    content: Object.freeze({
      minimumTemperatureCelsius: Math.min(...temperatures),
      maximumTemperatureCelsius: Math.max(...temperatures),
      condition: briefingHour.condition,
      precipitationLikely: isWetMeasurement(briefingHour),
      coveredThrough: zonedHour(Date.parse(lastHour.forecastAt), snapshot.timeZone) === lastLocalDayHour
        ? null
        : lastHour.forecastAt,
      event: outlook?.kind === 'steady' ? null : outlook,
    }),
  });
}
